### ISSUE TITLE
HB Inventario - Categorias

### ISSUE THREAD

**Issue by CrisTJ** [ProyectoIntegrador2018/MostlaInventario#15]
## Identificador
_HU-07_

## Descripción
Como USUARIO puedo identificar el equipo o software en inventario a través de categorías de tendencias para una rápida búsqueda. 

## To-Do
- [ ] Identificar las tendencias a utilizar 
- [ ] Agregar un campo a la base de datos que esté ligado con cada uno de los dispositivos o licencias de software 
- [ ] Generar el filtro por categorías 

## Criterios de Aceptación
El USUARIO debe de ser capaz de identificar la tendencia relacionada al dispositivo o licencia de software y deberá ser capaz de filtrar resultados en su búsqueda a partir de dichas categorías.
