### ISSUE TITLE
HB Instalación - Single sign-on 

### ISSUE THREAD

**Issue by CrisTJ** [ProyectoIntegrador2018/MostlaInventario#25]
## Identificador
_HU-17_

## Descripción
Como USUARIO puedo usar mis credenciales del Tecnológico de Monterrey para accesar a la plataforma a través de Google

## Conversacion 
- [x] Se debe tomar en cuenta que se espera utilizar esta plataforma en todos los campus del Tecnológico de Monterrey a futuro. 

## To-Do
- [x] Leer documentación de API de Google
- [x] Instalar componentes necesarios para usar API de Google
- [x] Diseñar implementación de login con API de Google
- [x] Implementar controlador de login usando API de Googl
--

## Criterios de Aceptación
Se conecta con la base de datos de ITESM con el API de Google para hacer single sign-on con la cuenta del Tec.
