### ISSUE TITLE
HB Reservaciones - Ver mis reservaciones activas/inactivas

### ISSUE THREAD

**Issue by JawnF** [ProyectoIntegrador2018/MostlaInventario#30]
## Identificador
_HU-0018_

## Descripción
**Como usuario puedo entrar a mi historial de reservaciones para ver mis préstamos pendientes y pasados.**

## Conversación
- Desde su perfil, el usuario puede ver la lista de sus reservaciones activas
- Desde su perfil, el usuario puede acceder al historial de sus reservaciones inactivas
- Las reservaciones activas son aquellas que todavía no inician o todavía no terminan.
- Las reservaciones inactivas son aquellas que fueron canceladas o ya terminaron (los productos se regresaron a Mostla).

## To-Do
- [ ] Implementar lógica para cargar reservaciones activas del usuario.
- [ ] Implementar lógica para cargar reservaciones inactivas del usuario.
- [ ] Implementar vista para desplegar reservaciones activas.
- [ ] Implementar vista para desplegar reservaciones inactivas.
- [ ] Implementar elemento de front end para cancelar una reservación.
- [ ] Implementar lógica para cancelar una reservación.
- [ ] Implementar lógica para cancelar un producto de una reservación.
- [ ] Implementar elemento de front end para cancelar un producto de una reservación.
- [ ] Implementar elemento de front end para confirmar antes de cancelar una reservación o producto.
- [ ] Dar estilo a la vista según el diseño general de la página.

## Criterios de Aceptación
- Que las reservaciones que se desplieguen sean las pertenecientes al usuario y que sean las correctas según su estado.
- Que se puedan cancelar reservaciones y sus productos individuales si el usuario lo desea.
- Que los cambios hechos a las reservaciones desde estas vistas se vean reflejados en la base de datos.
