### ISSUE TITLE
HB Inventario - Ver los productos existentes

### ISSUE THREAD

**Issue by fedehuguet** [ProyectoIntegrador2018/MostlaInventario#31]
### Identificador
HU-18

### Descripción
Como usuario ADMIN puedo ver los productos con su nombre, marca, categoría, fecha de creación y estatus.

### To-Do
- [x] Crear vista para ver los productos del inventario
- [x] Desarrollar servicio en el backend para activar/desactivar un producto

### Conversación

- [ ] Restringir el acceso a solo admin y admin por campus
- [ ] Mejorar el estilo de la página usando los patrones de diseño

### Criterios de aceptación
Una tabla que pueda traer la información básica del producto con botones de Editar y Activar/Eliminar producto.
