### ISSUE TITLE
HB Inventario - Crear productos

### ISSUE THREAD

**Issue by fedehuguet** [ProyectoIntegrador2018/MostlaInventario#32]
### Identificador
HU-19

### Descripción
Como usuario ADMIN puedo crear los productos con sus campos importantes nombre, marca, categoría, fecha de creación y estatus para guardar un nuevo producto.

### To-Do
- [x] Crear vista para guardar un nuevo producto
- [x] Desarrollar servicio en el backend para guardar el producto

### Conversación

- [ ] Restringir el acceso a solo admin y admin por campus
- [ ] Mejorar el estilo de la página usando los patrones de diseño
- [ ] Agregar relación con las Categorías de la base de datos

### Criterios de aceptación
Una forma para llenar los campos, con validación de que se llenen los requeridos y que muestra los errores cuando no se guardan correctamente.
