### ISSUE TITLE
HB Inventario - Editar producto

### ISSUE THREAD

**Issue by fedehuguet** [ProyectoIntegrador2018/MostlaInventario#33]
### Identificador
HU-20

### Descripción
Como usuario ADMIN puedo editar los productos con sus campos importantes nombre, marca, categoría, fecha de creación y estatus para modificar su información.

### To-Do
- [x] Crear vista para editar un nuevo producto
- [x] Desarrollar servicio en el backend para editar el producto

### Conversación

- [ ] Restringir el acceso a solo admin y admin por campus
- [ ] Mejorar el estilo de la página usando los patrones de diseño
- [ ] Agregar relación con las Categorías de la base de datos

### Criterios de aceptación
La forma debe precargar los datos del producto a editar y es posible modificarlos, el sistema valida que los campos sean correctos y de no serlo muestra los errores.
