### ISSUE TITLE
HB Instalación - Pagina de portada 

### ISSUE THREAD

**Issue by CrisTJ** [ProyectoIntegrador2018/MostlaInventario#34]
## Identificador
_HU-21_

## Descripción
Como USUARIO puedo observar una pagina de inicio para comprender el propósito del sitio donde estoy

## To-Do
- [ ] Generar la pagina de portada 
- [ ] Incluir descripción de Mostla 
- [ ] Incluir propósito de Mostla 

## Criterios de Aceptación
El usuario debe de ser capaz de comprender el propósito principal de la página web en donde se encuentra a partir de la información que se encuentra en la página de inicio.
