### ISSUE TITLE
Crear categoría

### ISSUE THREAD

**Issue by fedehuguet** [ProyectoIntegrador2018/MostlaInventario#46]
### Identificador
HU-22

### Descripción
Como usuario ADMIN puedo crear las categorías con su nombre.

### To-Do
- [x] Crear vista para guardar una nueva categoría
- [x] Desarrollar servicio en el backend para guardar la categoría

### Conversación

- [ ] Restringir el acceso a solo admin y admin por campus
- [ ] Mejorar el estilo de la página usando los patrones de diseño

### Criterios de aceptación
Una forma para llenar los campos, con validación de que se llenen los requeridos y que muestra los errores cuando no se guardan correctamente.
