### ISSUE TITLE
Crear unit

### ISSUE THREAD

**Issue by fedehuguet** [ProyectoIntegrador2018/MostlaInventario#47]
### Identificador
HU-23

### Descripción
Como usuario ADMIN puedo crear los units asociados con el producto y poner sus campos únicos e importantes como número serial y estatus.

### To-Do
- [x] Crear vista para guardar un nuevo unit
- [x] Desarrollar servicio en el backend para guardar el unit

### Conversación

- [ ] Restringir el acceso a solo admin y admin por campus
- [ ] Mejorar el estilo de la página usando los patrones de diseño
- [ ] Agregar relación con el Campus de la base de datos

### Criterios de aceptación
Una forma para llenar los campos, con validación de que se llenen los requeridos y que muestra los errores cuando no se guardan correctamente.
