### ISSUE TITLE
Editar categoría

### ISSUE THREAD

**Issue by fedehuguet** [ProyectoIntegrador2018/MostlaInventario#48]
### Identificador
HU-24

### Descripción
Como usuario ADMIN puedo editar las categorías.

### To-Do
- [x] Crear vista para editar una categoría
- [x] Desarrollar servicio en el backend para editar la categoría

### Conversación

- [ ] Restringir el acceso a solo admin y admin por campus
- [ ] Mejorar el estilo de la página usando los patrones de diseño

### Criterios de aceptación
La forma debe precargar los datos de la categoría a editar y es posible modificarlos, el sistema valida que los campos sean correctos y de no serlo muestra los errores.
