### ISSUE TITLE
Editar unit

### ISSUE THREAD

**Issue by fedehuguet** [ProyectoIntegrador2018/MostlaInventario#49]
### Identificador
HU-25

### Descripción
Como usuario ADMIN puedo editar los units con sus campos importantes número serial y estatus.

### To-Do
- [x] Crear vista para editar un unit
- [x] Desarrollar servicio en el backend para editar el unit
- [x] Restringir que no se pueda cambiar el producto al cual esta relacionado.

### Conversación

- [ ] Restringir el acceso a solo admin y admin por campus
- [ ] Mejorar el estilo de la página usando los patrones de diseño
- [ ] Agregar relación con el campus de la base de datos

### Criterios de aceptación
La forma debe precargar los datos del unit a editar y es posible modificarlos, el sistema valida que los campos sean correctos y de no serlo muestra los errores.
