### ISSUE TITLE
Ver las categorías

### ISSUE THREAD

**Issue by fedehuguet** [ProyectoIntegrador2018/MostlaInventario#50]
### Identificador
HU-26

### Descripción
Como usuario ADMIN puedo ver las categorías con su nombre.

### To-Do
- [x] Crear vista para ver las categorías del inventario
- [x] Desarrollar servicio en el backend para activar/desactivar una categoría

### Conversación

- [ ] Restringir el acceso a solo admin y admin por campus
- [ ] Mejorar el estilo de la página usando los patrones de diseño

### Criterios de aceptación
Una tabla que pueda traer la información básica de la categoría con botones de Editar y Activar/Eliminar.
