### ISSUE TITLE
Ver units

### ISSUE THREAD

**Issue by fedehuguet** [ProyectoIntegrador2018/MostlaInventario#51]
### Identificador
HU-27

### Descripción
Como usuario ADMIN puedo ver los units con su número serial, producto y estatus.

### To-Do
- [x] Crear vista para ver los units del inventario
- [x] Desarrollar servicio en el backend para activar/desactivar un unit

### Conversación

- [ ] Restringir el acceso a solo admin y admin por campus
- [ ] Mejorar el estilo de la página usando los patrones de diseño

### Criterios de aceptación
Una tabla que pueda traer la información básica del unit con botones de Editar y Activar/Eliminar.
