### ISSUE TITLE
HB Inventario - Recomendaciones

### ISSUE THREAD

**Issue by CrisTJ** [ProyectoIntegrador2018/MostlaInventario#9]
## Identificador
_HU-1_

## Descripción
Como USUARIO puedo observar conjuntos de dispositivos recomendados para observar nuevas tendencias.

## To-Do
- [ ] Guardar combinaciones de renta de equipo
- [ ] Identificar patrones de renta
- [ ] Sugerir a USUARIO equipo a rentar a partir de lo que tiene en su carrito de reservación

## Criterios de Aceptación
El sistema es capaz de sugerir equipo dependiendo de la tendencia a rentar de otros USUARIOS.
